config/routes.rb
Rails.application.routes.draw do

  root to: "users#index"

  get 'sessions/new'

  post 'sessions/create'

  delete '/sessions', to: "sessions#destroy"

  # TODO: research how to use only certain CRUD functions in this resource - JC
  resources :categories

  resources :performers

  resources :users

end

app/views/partials/_footer.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="#"></a>
	    </div>

			    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			      <ul class="nav navbar-nav">
              <!--TODO: Please remove any non-functioning links from deployment versions - JC  -->
			      	<li><%= link_to "Home", "/" %></li>
			      	<li><%= link_to "Trust & Safety", "/" %></li>
			      	<li><%= link_to "Tell your Friends!", "/" %></li>
			      	<li><%= link_to "Our Team", "/" %></li>
			      	<li><%= link_to "Contact Us", "/" %></li>
			      </ul>
			    </div><!-- /.navbar-collapse -->

  </div><!-- /.container-fluid -->
</nav>

app/views/partials/_navbar.html.erb
	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="#"></a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	      	<li><%= link_to "Home", "/" %></li>
	      	<li><%= link_to "Browse Performers", performers_path %></li>
	      	  	<% if current_user && (current_user.performer == true) %>
			      	  	<li><%= link_to "Profile Page", user_path(current_user.id) %></li>
			      	    <li><%= link_to "Logout", sessions_path, method: :delete %></li>
									<p>Check your database privileges</p>

									<li><%= link_to "Performer Profile", performer_path(




										Performer.where(user_id: current_user.id).first.id
			      	    ) %></li>
	      	  	<p> <%=
%> </p>

	      	  	<% elsif current_user && (current_user.performer == false) %>
			      	  	<li><%= link_to "Profile Page", user_path(current_user.id) %></li>
			      	    <li><%= link_to "Logout", sessions_path, method: :delete %></li>
	      	  	<% else %>
		     			 <li><%= link_to "Sign Up", "/users/new" %></li>
		     			 <li><%= link_to "Login", "/sessions/new" %></li>
		      	<% end %>
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>