config/routes.rb
Rails.application.routes.draw do

  root to: "users#index"

  get 'sessions/new'

  post 'sessions/create'

  delete '/sessions', to: "sessions#destroy"

  # TODO: research how to use only certain CRUD functions in this resource - JC
  resources :categories

  resources :performers

  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
	validates :avatar,
		attachment_content_type: {content_type: /\Aimage\/.*\Z/ }
    has_secure_password
	has_many :performers
    has_attached_file :avatar, styles: { thumb: "100x100!" }, :default_style => :thumb, default_url: "/images/:style/missing.png"


    def self.confirm(params)
        @user = User.find_by({email: params[:email]})
        @user.try(:authenticate, params[:password])
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
      @users = User.all
      render :index
  end

  def show
    # TODO: make use of your nice id var below - JC
      id = params[:id]
      @user = User.find(params[:id])
      if current_user.id == @user.id
        render :show
      else
        redirect_to root_path
      end
  end

  def new
      @user = User.new
  end

  def create
      @user = User.create(user_params)
      if @user.performer && @user.save
          login(@user)
          redirect_to new_performer_path
      elsif @user.save
          login(@user)
          flash[:success] = "Welcome!"
          redirect_to("/users/#{@user.id}")
      else
          flash[:danger] = "It failed!"
          render 'new'
      end
  end


  def edit
      @user = User.find(params[:id])
    if @user.id == current_user.id
        render :edit
    else
      redirect_to root_path
    end
  end

  def update
      user_id = params[:id]
      user = User.find(user_id)
      # get updated data
      # TODO: please use your user_params function here - JC
      updated_attributes = params.require(:user).permit(:first_name, :last_name, :email, :password, :avatar)

      # update the client_
      user.update_attributes(updated_attributes)
      user.save(validate: false)
      #redirect to show
      redirect_to "/users/#{user.id}"  # <-- go to show
    end

    # TODO: breaks the server :( Couldn't navigate site after I deleted account - JC
  def destroy
    id = params[:id]
    user = User.find(id)
    user.destroy
    redirect_to root_path
  end

private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :performer, :avatar)
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/about.html.erb
<div class='container'>

		<div class="row">
			<div><img src="http://placekitten.com/g/150/150" class="img-rounded bio-img"></div>
			<div class="bio"><strong>Lisa Lehrman</strong> is an awesome web developer in San Francisco. She was the chief kitten wrangler for <strong>Encore</strong>.</div>
		</div>
		<div class="row">
			<div><img src="http://placekitten.com/g/150/150" class="img-rounded bio-img"></div>
			<div class="bio"><strong>Darragh Monaghan</strong> is an awesome web developer in San Francisco. He was the circus strongman for <strong>Encore</strong>.</div>
		</div>
		<div class="row">
			<div><img src="http://placekitten.com/g/150/150" class="img-rounded bio-img"></div>
			<div class="bio"><strong>Neil Rayos</strong> is an awesome web developer in San Francisco. He was the caped crusader for <strong>Encore</strong>.</div>
		</div>
		<div class="row">
			<div><img src="http://placekitten.com/g/150/150" class="img-rounded bio-img"></div>
			<div class="bio"><strong>Heather Stenson</strong> is an awesome web developer in San Francisco. She was the manitee specialist for <strong>Encore</strong>.</div>
		</div>
		<!-- <h4>4 members, battling 1 partially working site</h4>
		<p>Not much fun was had</p> -->
</div>

app/views/users/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>User#destroy</h1>
<p>Find me in app/views/user/destroy.html.erb</p>

app/views/users/edit.html.erb
<%= stylesheet_link_tag "users" %>

<div class="form-container">
<h1 class="edit-header">Edit User</h1>

  <div class="form-group">
    <%= form_for @user do |f| %>
	<%= f.email_field :email, placeholder: 'Email', class: "users-new-input", required: true %></br> 
    <%= f.text_field :first_name, placeholder: 'First Name', class: "users-new-input", required: true %><br>
    <%= f.text_field :last_name, placeholder: 'Last Name', class: "users-new-input", required: true %><br>
    <%= f.password_field :password, placeholder: 'Password', class: "users-new-input", required: true %><br>
     <%= f.submit "edit", class: "ghost-button" %>
 <% end %>
	</div>
  </div>
 

app/views/users/index.html.erb
<div class="jumbotron">
  <div class="container">
  <h1>Find a performer near you</h1>
  <p>The best local performers.</p>
  <button type="button" class="btn btn-default btn-lg btn-block"><%= link_to "Search All Perfomers", performers_path %></button>
  </div>
</div>

<div class="container">
<!-- row of columns -->
  <div class="col-md-4">
    <h3>Hire performers.</h3>
     <!-- TODO: be careful when hot-linking content, original site can change their content at will. Consider hosting your own content. - JC -->
    <div><img class="perf" src="http://i.cdn.talentegg.ca/incubator/wp-content/uploads/bourke3.jpg">
    </div>
    <p>Make it memorable</p>
    <button type="button" class="btn btn-sm btn-info"><%= link_to "Musical Acts", "/categories/1" %></button>
  </div>
<!-- row of columns -->
<div class="col-md-4">
    <h3>Do you love magic?</h3>
    <!-- TODO: be careful when hot-linking content, original site can change their content at will. Consider hosting your own content. - JC -->
    <div><img class="perf" src="http://www.neurosciencemarketing.com/blog/wp-content/uploads/2010/11/magician-cards.jpg">
    </div>
      <p>Browse magicians and clowns near you.</p>

      <button type="button" class="btn btn-sm btn-info"><%= link_to "Comedy Acts", "/categories/2" %></button>
      </div>
    <!-- row of columns -->
<div class="col-md-4">
    <h3>Looking for a laugh?</h3>
    <!-- TODO: be careful when hot-linking content, original site can change their content at will. Consider hosting your own content. - JC -->
    <div><img class="perf" src="http://nickshell1983.files.wordpress.com/2011/01/stand-up-comedy-mic.jpg">
    </div>
      <p>The funniest comics are at your event.</p>
      <button type="button" class="btn btn-sm btn-info"><%= link_to "Circus Acts", "/categories/3" %></button>
    </div>
</div>
<br>

app/views/users/new.html.erb
<%= stylesheet_link_tag "users" %>
  <div id="main-container" class="container">
    <div class="row">

      <div id="content" class="col-md-12">
        <div class="form-container">
        
            <h2 class="form-signin-heading">Sign Up Now!</h2>
            <%= form_for @user do |f| %> 
            <div class="form-group">
              <%= f.email_field :email, placeholder: 'Email', class: "form-control", required: true %>
            </div>
            <div class="form-group">
              <%= f.text_field :first_name, placeholder: 'First Name', class: "form-control", required: true %>
            </div>
            <div class="form-group">
              <%= f.text_field :last_name, placeholder: 'Last Name', class: "form-control", required: true %>
            </div>
            <div class="form-group">
              <%= f.password_field :password, placeholder: 'Password', class: "form-control", required: true %>
            </div>
            <div class="form-group">
              <%= f.file_field :avatar, class: "form-control" %>
              <p class="help-block">Upload a user avatar!</p>
            </div>
            <div class="form-group">
              <h2>Want to be a performer? <%= f.check_box(:performer) %></h2> 
              <p class="helper-block">Tick the box once you've finished this form to go to the performer sign up page!
              </p>
            </div>
            <%= f.submit "Signup!", class: "ghost-button" %>
              <% end %>
             </div>
        </div>
      </div>
    </div>
</div> 

app/views/users/show.html.erb
<div class="profile container">
  <div class="row">
    <div class="col-md-10 col-xs-10">
      <div class="well panel panel-default">
        <div class="panel-body">
          <div class="row">
            <div class="col-xs-12 col-md-4 text-center">
                <%= image_tag @user.avatar.url(:thumb) %>
            </div>
            <div class="col-xs-12 col-md-4">
                <h2>Welcome, <%= @user.first_name %></h2>
                <strong>Member since: </strong><%= @user.created_at.strftime("%d %b. %Y") %>
            </div>
        <!-- col -->
        <!-- col -->
            <!--/col-->
            <div class="col-xs-12 col-md-4">
                  <%= button_to "Edit", edit_user_path, method: :get, class: "btn btn-warning" %>
                  <%= button_to "Delete", user_path, method: :delete, class: "btn btn-danger"  %>
            </div>
            <!--/col-->
          </div>
          <!--/row-->
        </div>
        <!--/panel-body-->
      </div>
      <!--/panel-->
    </div>
    <!--/col--> 
  </div>
  <!--/row--> 
</div>
<!--/container-->

app/views/users/update.html.erb
<h1>User#update</h1>
<p>Find me in app/views/user/update.html.erb</p>