config/routes.rb
Rails.application.routes.draw do

  root to: "users#index"

  get 'sessions/new'

  post 'sessions/create'

  delete '/sessions', to: "sessions#destroy"

  # TODO: research how to use only certain CRUD functions in this resource - JC
  resources :categories

  resources :performers

  resources :users

end

app/models/performer.rb
class Performer < ActiveRecord::Base
	belongs_to :user

	has_attached_file :perfavatar, styles: { thumb: "100x100!" }, :default_style => :thumb, default_url: "/images/:style/missing.png"	
	validates :perfavatar,
		attachment_content_type: {content_type: /\Aimage\/.*\Z/ }

	has_attached_file :image1, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image1, content_type: /\Aimage\/.*\Z/

     has_attached_file :image2, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
     validates_attachment_content_type :image2, content_type: /\Aimage\/.*\Z/

     has_attached_file :image3, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
     validates_attachment_content_type :image3, content_type: /\Aimage\/.*\Z/

     scope :category_id, -> (category_id) {where category_id: category_id }
     
     extend FriendlyId
     friendly_id :performer_name, use: [:slugged, :finders]

end

app/controllers/performers_controller.rb
# TODO: please remove commented out code from deployment version - JC

# TODO: check out the sitch with photos loading.
# TODO: clean up the layout for the media
class PerformersController < ApplicationController
  def index
    @performers = Performer.all
  end

  def new
    @performer = Performer.new
  end

  def create
    # @performer = current_user.performer.new(performer_params)
    @performer = Performer.new(performer_params)
    @performer.user_id = current_user.id
    # @user = current_user.performer_id << @performer.id
      if @performer.save
        flash[:success] = "Welcome!"
        redirect_to("/performers/#{@performer.id}")
      else
        flash[:danger] = "It failed!"
        render 'new'
      end
  end

  # def show
  #   # need to connect user's performer_id and the performer id fields
  #   @performer = Performer.find_by_id(params[:id]) #this line should be finding the performer by the performer id

  #   category_id = @performer.category_id #should be finding the performer's category id
  #   @category = Category.find_by_id(category_id) #should be querying the cat. database using category_id

  #   @user = User.find_by_id(@performer.user_id) #should be finding the user id by the performer_id
  #   @video1 = @performer.video1 #finding the first video for the performer
  # end


  def show
    # TODO: please remove terminal logging from deployment version - JC
    puts "PARAMS" , params.inspect
    @performer_id = params[:id]
    # puts "PERF ID: ", @performer_id
    @performer = Performer.find(@performer_id)
    # puts "PERF OBJECT: ", @performer.inspect
    # @user_id = @performer.user_id
    # puts "USER ID: ", @user_id
    # @user = User.find(@user_id)
    # puts "USER OBJECT: ", @user.inspect

    #@performers = Performer.where(user_id: user_found.user_id)
    #@performer = @user_found.performers.collect(&:id)

    # #@performer = Performer.find_by_id(@performer_id)

    # @user = User.find_by_id(@performer.user_id) #should be finding the user id by the performer_id
    # binding.pry
    # @video1 = @performer.video1 #finding the first video for the performer

  end






  def edit
    @performer = Performer.find(params[:id])
        if current_user.id  == @performer.user_id
            render :edit
        else
            redirect_to root_path
        end
    end

  def update
      @performer = Performer.find(params[:id])
          if @performer.update(performer_params)
            redirect_to performer_path(@performer)
          else
            render :edit
          end
    end

  def destroy
    if current_user.id  == @performer.user_id
      id = params[:id]
      performer = Performer.find(id)
      performer.destroy
    else
      redirect_to root_path
  end

  end

  private
  # TODO: please pat yourself on the back for keeping your performers safe - JC
  def performer_params
    params.require(:performer).permit(:user_id, :performer_name, :performer_email, :city, :category_id, :subcategory, :hourly_rate, :description, :perfavatar, :image1, :image2, :image3, :video1, :video2, :video3)
  end
end

app/helpers/performers_helper.rb
module PerformersHelper

  def embed(youtube_url)
    youtube_id = youtube_url.split("=").last
    content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}")
  end

end

app/views/performers/create.html.erb
<h1>Performer#create</h1>
<p>Find me in app/views/performer/create.html.erb</p>

app/views/performers/edit.html.erb
<div class="container">
<h1 class="edit-performer-header">Edit Your Profile</h1>

<div class="col-md-8">

      <%= form_for @performer do |f| %>
      <div class="form-group">
        <%= f.text_field :performer_name, placeholder: "Your name or group name", class: "form-control" %>
      </div>
    
      <div class="form-group">
        <%= f.email_field :performer_email, placeholder: "Your business email address", class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.text_field :city, placeholder: "Where are you?", class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.text_field :subcategory, placeholder: "Your act type",  class: "form-control" %>
      </div>
        
      <div class="form-group">
        <%= f.text_area :description, placeholder: "Describe your act for us! Min. 30, max. 500 characters.", required: true, cols: 100, rows: 4 %>
      </div>
        
    <div class="form-group">
      <%= f.select :category_id, [['Musical Act', 1], ['Comedy Act', 2], ['Circus Act', 3]] %>

      <%= f.select :hourly_rate, [['$1-25 per hour', '$1-25 per hour'], ['$26-50 per hour', '$26-50 per hour'], ['$51-75 per hour', '$51-75 per hour'], ['$76-100 per hour', '$76-100 per hour'], ['$101-150 per hour', '$101-150 per hour']] %>
    </div>

      <div class="form-group">
        <%= f.file_field :perfavatar, class: "form-control" %>
        <p class="help-block">Upload your performer avatar.</p>
      </div>
      <div class="form-group">
        <%= f.file_field :image1, class: "form-control" %>
        <p class="help-block">Upload your first user image.</p>
      </div>
      <div class="form-group">
        <%= f.file_field :image2, class: "form-control" %>
        <p class="help-block">Upload your second user image.</p>
      </div>  
      <div class="form-group">
        <%= f.file_field :image3, class: "form-control" %>
        <p class="help-block">Upload your third user image.</p>
      </div>
        
      <div class="form-group">
        <%= f.text_field :video1, placeholder: "Enter a URL link from YouTube", class: "form-control" %>
      </div>  
      <div class="form-group">
        <%= f.text_field :video2, placeholder: "Enter a URL link from YouTube", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.text_field :video3, placeholder: "Enter a URL link from YouTube", class: "form-control" %>
      </div>  


    <%= f.submit "Edit", class: "ghost-button" %>

</div>
<% end %>
</div>

app/views/performers/index.html.erb
<div class="container">

	<div class='row'>
		<div class='col-md-2'></div>
		<h3 class='col-md-8' align='center'>Performer options to bring every event to life!</h3>
		<div class='col-md-2'></div>
	</div><br>

	<% @performers.each do |performer| %>
	<div class='row panel panel-default'>
		<div class='col-sm-10 col-md-4' style="padding-top:50px;padding-left:75px;">
			<%= image_tag(performer.perfavatar, class: "cat_show_avatar") %>
		</div>
		<div class='col-sm-10 col-md-8'>
			<h3> <%= link_to performer.performer_name, performer_path(performer.slug) %></h3>
			<strong>City:</strong> <%= performer.city %><br>
			<strong>Category:</strong>

			<% if performer.category_id == 1 %>
				<%= "Musical Act" %>
			<% elsif performer.category_id == 2 %>
				<%= "Comedy Act" %>
			<% else %>
				<%= "Circus Act" %>
			<% end %><br>

			<strong>Subcategory:</strong> <%= performer.subcategory %><br>
			<strong>Price:</strong> <%= performer.hourly_rate %><br>
			<strong>Description:</strong> <%= performer.description %><br>
			<% if current_user %>
				<strong>Contact This Performer: </strong><a href="mailto:<%= performer.performer_email %>"><%= performer.performer_email %></a><br><br>
			<% else %>
				<strong><%= link_to "Login now to contact this performer!", "/sessions/new" %></strong>
				<br>
				<br>
			<% end %>
			
		</div>
	</div>
	<% end %>

</div>

app/views/performers/new.html.erb
<%= stylesheet_link_tag "users" %>
 <div id="main-container" class="container">
  	<div class="row">
    	<div class="col-xs-3">
			<h2 class="make-some-money">Sign Up Now</h2>
			<p>	Are you an amazing juggler? Do you make all of your friends laugh at parties? Put those talents to use! Sign up as a performer on Encore and you can connect with individuals and organizations that will pay you for your services.<p>
			<p><strong>Here's how it works:</strong> Fill out the form and upload media so that our users can see what you can do. When a user contacts you, you'll work with them to arrange the details. Good luck! </p>
    	</div>

 		<div id="content" class="col-xs-9 newperformercontent">
			<h1 class="make-some-money">Become an Encore performer!</h1>	
   	
			<%= form_for @performer do |f| %>
			<div class="form-group">
				<%= f.text_field :performer_name, placeholder: "Your name or group name", class: "form-control", required: true %>
			</div>
		
			<div class="form-group">
				<%= f.email_field :performer_email, placeholder: "Your business email address", class: "form-control", required: true %>
			</div>
			
			<div class="form-group">
				<%= f.text_field :city, placeholder: "Where are you?", class: "form-control", required: true %>
			</div>
			
			<div class="form-group">
				<%= f.text_field :subcategory, placeholder: "Your act type",  class: "form-control", required: true %>
			</div>
				
			<div class="form-group">
				<%= f.text_area :description, placeholder: "Describe your act for us! Min. 30, max. 500 characters.", required: true, cols: 100, rows: 4 %>
			</div>
				
		<div class="form-group">
			<%= f.select :category_id, [['Musical Act', 1], ['Comedy Act', 2], ['Circus Act', 3]], required: true %>

			<%= f.select :hourly_rate, [['$1-25 per hour', '$1-25 per hour'], ['$26-50 per hour', '$26-50 per hour'], ['$51-75 per hour', '$51-75 per hour'], ['$76-100 per hour', '$76-100 per hour'], ['$101-150 per hour', '$101-150 per hour']], required: true %>
		</div>

			<div class="form-group">
				<%= f.file_field :perfavatar, class: "form-control" %>
				<p class="help-block">Upload your performer avatar.</p>
			</div>
			<div class="form-group">
				<%= f.file_field :image1, class: "form-control" %>
				<p class="help-block">Upload your first user image.</p>
			</div>
			<div class="form-group">
				<%= f.file_field :image2, class: "form-control" %>
				<p class="help-block">Upload your second user image.</p>
			</div>	
			<div class="form-group">
				<%= f.file_field :image3, class: "form-control" %>
				<p class="help-block">Upload your third user image.</p>
			</div>
				
			<div class="form-group">
				<%= f.text_field :video1, placeholder: "Enter a URL link from YouTube", class: "form-control" %>
			</div>	
			<div class="form-group">
				<%= f.text_field :video2, placeholder: "Enter a URL link from YouTube", class: "form-control" %>
			</div>
			<div class="form-group">
				<%= f.text_field :video3, placeholder: "Enter a URL link from YouTube", class: "form-control" %>
			</div>	
		

		<%= f.submit "Sign Up Your Act!", class: "ghost-button" %>

		<% end %>
	
   </div>
</div>
</div>
</div>

app/views/performers/show.html.erb
<div class="container">

	<%= link_to "Log Out", "/sessions", method: :delete %><br>

	<%= link_to "Edit Profile", edit_performer_path, method: :get %>


 <% if correct_user(@performer) %>
  <%= button_to "Delete", performer_path, method: :delete %>
  <% end %>

  <div>
				
        <%= image_tag(@performer.perfavatar) %>
  </div>

	<div>
    <% if current_user %>
      <p> <%= current_user.first_name %> </p>
		  <strong>Email:</strong> <%= @performer.performer_email %>
    <% else %>
      <strong>Email:</strong><%= "Sign Up to See This Performer Email!" %>
    <% end %>
	</div>
	<div>
		<h1><%= @performer.performer_name %></h1>
		<h3><%= @performer.city %></h3>
		<strong>Category:</strong>  - <%= @performer.subcategory %>
		<br>
		<strong>Hourly Rate:</strong> <%= @performer.hourly_rate %>
	</div>

	<div>
		<strong>Description:</strong> <%= @performer.description %>
	</div>
	<br>

<div id="performer-img" class="carousel slide" data-ride="carousel">
 <!-- Indicators -->
 <ol class="carousel-indicators">
   <li data-target="#performer-img" data-slide-to="0" class="active"></li>
   <li data-target="#performer-img" data-slide-to="1"></li>
   <li data-target="#performer-img" data-slide-to="2"></li>
   <li data-target="#performer-img" data-slide-to="3"></li>
 </ol>

 <!-- Wrapper for slides -->
 <div class="carousel-inner" role="listbox">
   <div class="item active">
     <img src="<%= @performer.image1 %>">
   </div>

   <div class="item">
     <img src="<%= @performer.image2 %>">
   </div>

   <div class="item">
     <img src="<%= @performer.image3 %>">
   </div>

 </div>

 <!-- Left and right controls -->
 <a class="left carousel-control" href="#performer-img" role="button" data-slide="prev">
   <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
   <span class="sr-only">Previous</span>
 </a>
 <a class="right carousel-control" href="#performer-img" role="button" data-slide="next">
   <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
   <span class="sr-only">Next</span>
 </a>
</div>

 <br><br>

<div id="performer-vid" class="carousel slide" data-ride="carousel" data-interval="false">

 <!-- Indicators -->
 <ol class="carousel-indicators">
   <li data-target="#performer-vid" data-slide-to="0" class="active"></li>
   <li data-target="#performer-vid" data-slide-to="1"></li>
   <li data-target="#performer-vid" data-slide-to="2"></li>
   <li data-target="#performer-vid" data-slide-to="3"></li>
 </ol>

 <!-- Wrapper for slides -->
 <div class="carousel-inner" role="listbox">
   <div class="item embed-container active">
      <%= embed(@performer.video1) %>
   </div>

   <div class="item embed-container">
      <%= embed(@performer.video2) %>
   </div>

   <div class="item embed-container">
     <%= embed(@performer.video3) %>
   </div>
 </div>

 <!-- Left and right controls -->
 <a class="left carousel-control" href="#performer-vid" role="button" data-slide="prev">
   <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
   <span class="sr-only">Previous</span>
 </a>
 <a class="right carousel-control" href="#performer-vid" role="button" data-slide="next">
   <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
   <span class="sr-only">Next</span>
 </a>
</div>


	</div>

app/views/performers/update.html.erb
<h1>Performer#update</h1>
<p>Find me in app/views/performer/update.html.erb</p>